/*CREATE A DATABASE IF NOT EXISTS*/
CREATE DATABASE IF NOT EXISTS banner_object_info;
USE banner_object_info;
/*CREATE A TABLE FOR BANNER OBJECT STORAGE*/
CREATE TABLE IF NOT EXISTS banner(
  id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
  starttime DATETIME NOT NULL,
  endtime DATETIME NOT NULL,
  targetip INT(11) UNSIGNED NOT NULL, 
  banner_url VARCHAR(10900) DEFAULT CHARACTER SET utf8 NOT NULL,
  dest_url VARCHAR(10900) DEFAULT CHARACTER SET utf8 NOT NULL,
  show_status BOOLEAN,
  tstmp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  UNIQUE (starttime, endtime, targetip)
)
